### ISSUE TITLE
Cannot find name 'html'

### ISSUE THREAD

**Issue by cvharris** [mjbvz/vscode-lit-html#18]
All the examples have 'html' prefixed to the template string but not how to declare `html` as something to use. I'm working on SPFX extensions and have to use template inline strings everywhere to manipulate `innerHtml` and would love to make this work.

```javascript
this.domElement.innerHTML = `
  <div class="${styles.app}">
    <!-- ... -->
  </div>
`
```

If I just add 'html' before the template string I get a syntax error, which makes sense cause it looks like a variable that isn't being declared anywhere.

Do I literally have to add `declare var html` somewhere to make this work?

Coincidentally, there's some nice HTML-in-JS-string-literal highlighting just in this Github post, and I didn't need an extension or funny keyword to make it work 😉

**Comment by mjbvz** [comment]
`html` typically comes from the lit-html library or similar. Support for html in untagged template strings is tracked by #14

**Comment by alexsasharegan** [comment]
I'm having trouble with this error as well. I have the vscode plugin installed, `typescript-lit-html-plugin` added to the project's dev dependencies (0.2.0), the workspace typescript activated (2.7.2), and the plugin entry added to `tsconfig.json`. I've also tried adding `lit-html` to my dev dependencies.

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "lib": ["dom", "esnext"],
    "jsx": "preserve",
    "target": "es5",
    "module": "esnext",
    "moduleResolution": "node",
    "importHelpers": false,
    "allowJs": true,
    "experimentalDecorators": true,
    "strictNullChecks": true,
    "noImplicitAny": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "removeComments": true,
    "preserveConstEnums": false,
    "sourceMap": true,
    "skipLibCheck": true,
    "plugins": [{ "name": "typescript-lit-html-plugin" }]
  },
  "include": ["src/js"],
  "exclude": ["node_modules", "src/js/libs"]
}
```

![image](https://user-images.githubusercontent.com/16269252/37230945-6a42c6d8-23a6-11e8-976b-e137b79df38e.png)

I initially started down this path purely for syntax highlighting. Ideally, I was hoping these tags would be stripped later since the template is fine as is minus the DX for syntax highlighting. I'm a little lost at this point.
