### ISSUE TITLE
The collapse buttons doesn't appear

### ISSUE THREAD

**Issue by abdonrd** [mjbvz/vscode-lit-html#35]
The collapse buttons doesn't appear.

![jul-03-2018 12-26-44](https://user-images.githubusercontent.com/1007051/42214659-64907fd4-7ebc-11e8-8186-5f83fa9e09a6.gif)

**Comment by justinribeiro** [comment]
This is because the lit-html lang service doesn't implement `FoldingRangeProvider`. There is a proposal for adding this to language server protocol (see [Microsoft/vscode-languageserver-protocol-foldingprovider](https://github.com/Microsoft/vscode-languageserver-protocol-foldingprovider) for more information), but I don't know the current state of being able to actually implement now.

**Comment by mjbvz** [comment]
Published 1.5.0 with support for folding

**Comment by abdonrd** [comment]
Awesome, thanks! 👏

**Comment by leosdad** [comment]
Sorry for reviving an old topic, but as of version 1.11.1 the code folding still doesn't work. Is there something else we should know to make it work?

**Comment by mjbvz** [comment]
#73
