### ISSUE TITLE
The color picker doesn't work

### ISSUE THREAD

**Issue by abdonrd** [mjbvz/vscode-lit-html#36]
The color picker doesn't work.

![jul-03-2018 12-28-26](https://user-images.githubusercontent.com/1007051/42214735-a71ec81a-7ebc-11e8-9a7b-984d69a14d89.gif)

**Comment by justinribeiro** [comment]
I believe this is because I didn't implement the switch case in `getQuickInfoAtPosition` to do hover (it actually doesn't return any hover info for the position for css properties, which makes sense given the code). I'm working on fix to the upstream.

**Comment by mjbvz** [comment]
@justinribeiro I don't think it will work even if you implement `getQuickInfoAtPosition`. As a typescript plugin, there is currently no way to tell VS Code that you are providing color information. This depends on https://github.com/Microsoft/TypeScript/issues/21999

This also effects the styled-plugin https://github.com/styled-components/vscode-styled-components/issues/95

**Comment by justinribeiro** [comment]
Much appreciate the additional context @mjbvz, I didn't locate that ticket when I was looking around. Thanks for saving me some head scratching. :-)

I'll update `getQuickInfoAtPosition` regardless (since I missed that in the first patch), and if something changes in the upstream for that TypeScript ticket, I'm happy to revisit.
